jdbc:
    driver : org.postgresql.Driver

movie :
  randomCount: 1

# 60 * 60 * 4 =4h       14400000
# 60 * 60 * 24 = 1d     86400000
cache:
  initialDelay : 10000
  fixedDelay   : 14400000
  fixedDelayCountry: 86400000

dbcp :
    initialSize : 1
    maxTotal    : 2
    validationQuery : Select 1 

liquibase: 
  change-log : classpath:db.changelog.xml