jdbc:
    driver : org.postgresql.Driver

movie :
  randomCount: 1

cache:
  initialDelay : 10000
  fixedDelay   : 14400000

dbcp :
    initialSize : 1
    maxTotal    : 2
    validationQuery : Select 1 